name=input ("what is your name?")
print (name)
age=input ("how old are you?")
print (age)
color=input ("what is your favorite color?")
print (color)
food=input ("what is your favorite food?")
print (food)
animal=input ("what is your favorite animal?")
print (animal)
movie=input ("What is your favorite movie?")
print (movie)
power=input ("What is your favorite superpower?")
print (power)
word=input ("What is your favoroite word?")
print (word)
science=input ("What is your favorite type of science?")
print (science)
subject=input ("What is your favorite subject?")
print (subject)
travel=input ("If you could go anywhere, where would you go?")
print (travel)
restaraunt=input ("What is your favorite restaraunt?")
print (restaraunt)
fruit=input ("What is your favorite fruit?")
print (fruit)
game=input ("What is your favorite video game?")
print (game) 
artist=input ("Who is your favorite artist?")
print (artist)
song=input ("What is your favorite song?")
print (song)
mlp=input ("What is your favorite My Little Pony?")
print (mlp)
hair=input ("How would ou describe your hair?")
print(hair) 

