noun=input ("Put in a noun")
print (noun)
name=input ("Put in a name")
print (name)
famous= input ("Put in a name of a famous person")
print (famous)
verb=input ("Put in a verb")
print (verb)
adverb=input ("Put in an adverb")
print (adverb)
adjective=input ("Put in an adjective")
print (adjective)
nounA=input ("Pick ANOTHER noun")
print (nounA)
print ("I can't believe you kidnapped my "  + noun +  " cried "  +  name)
print ("You don't need a"  + noun +  "for a "  + famous +  "concert said Crazy Jay")
print (name +  "started to"  + verb + adverb)
print ("You are so"  + adjective +  "sometimes"  + name +  "said Crazy Jay")
print ("But I have to bring it or I will be trapped in the"  + nounA +   "FOREVER cried \n" + name)

print ("")