name=input("What is your name?")
print(name)
age=input("What is your age?")
print(age)
color=input("What is your favorite color?")
print (color)
animal=input("What is your favorite animal?")
print (animal)
naturalDisaster=input("What is your favorite natural disaster?")
print (naturalDisaster)
shoes=input("What shoes are you wearing?")
print (shoes)