name1= input ("put in your name")
print (name1)
gender1= input ("put in your gender")
print (gender1)
if ("girl"):
    (gender2)=("her")
    (gender3)=("she")
if ("boy"):
    (gender2)=("his")
    (gender3)=("he")
noun1= input("put in a noun")
print (noun1)
verb1= input("put in a verb")
print (verb1)
noun2= input("put in a noun")
print (noun2)
place1= input("put in a place")
print (place1)
name2= input("put in the name of someone in this room")
print (name2)
print (name1 + " got a brand new" + noun1)
print ("One day " + name1 + " was " + verb1 + " with " + (gender2) + " new " + noun1 + " when " + gender3 + " heard a loud " + noun2)
print (name1 + " ran outside to see that he was in a different place")